### ISSUE TITLE
[Bug] 0dcce451 breaks A5 cross-core TPUSH compilation with missing TInsertMode::NZ_PLUS_1

### ISSUE THREAD

**Issue by lwDavid** [PTO-ISA/pto-isa#94]
### Component

A5 backend (`include/pto/npu/a5/*`), cross-core `TPUSH` / V2C path

### Description

A5 cross-core kernels stop compiling starting from commit `0dcce451ea95f7fd42e090c559dfaacc3b04494f`.

The failure happens because `include/pto/npu/a5/TInsert.hpp` no longer defines `TInsertMode::NZ_PLUS_1`, but `include/pto/npu/a5/TPush.hpp` still references `TInsertMode::NZ_PLUS_1` in `pushVec2MatFiFo()` for the split-M vector-to-matrix FIFO path.

### Steps to Reproduce

1. Checkout `pto-isa` at `0dcce451ea95f7fd42e090c559dfaacc3b04494f`.
2. Use this ISA revision with PyPTO on A5 hardware.
3. Run:

```bash
pytest tests/st/runtime/test_cross_core.py -k test_tpush_tpop_v2c_updown -v --forked --device 0 --platform a5
```

I also reproduced this with the full cross-core suite:

```bash
pytest tests/st/runtime/test_cross_core.py -v --forked --device 0 --platform a5
```

### Expected Behavior

The A5 cross-core test should compile and run successfully.

This works with last known good commit `54c7c6dcfab5c21d523de6939bf8d7b305c5a804`.

### Actual Behavior

Compilation fails in the A5 ISA headers with:

```text
error: no member named 'NZ_PLUS_1' in 'pto::TInsertMode'
```

The failing reference is in `include/pto/npu/a5/TPush.hpp` inside `pushVec2MatFiFo()`, where the split-M path still instantiates `TINSERT_IMPL<TInsertMode::NZ_PLUS_1>(...)`.

### Git Commit ID

First bad commit: `0dcce451ea95f7fd42e090c559dfaacc3b04494f`

Last good commit: `54c7c6dcfab5c21d523de6939bf8d7b305c5a804`

### NPU Kind

Ascend 950 (A5)

### Host Platform

Linux (aarch64)

### Additional Context

The regression range is:

- Good: `54c7c6dcfab5c21d523de6939bf8d7b305c5a804`
- Bad: `0dcce451ea95f7fd42e090c559dfaacc3b04494f` (`add Tinsert vec-to-vec, ub2l1 unaligned, fp4/hif8 dtype`)

What changed across that boundary:

- In `include/pto/npu/a5/TInsert.hpp`, `TInsertMode` was reduced to only `SPLIT2` and `SPLIT4`.
- In `include/pto/npu/a5/TPush.hpp`, the A5 vector-to-matrix FIFO path still uses `TInsertMode::NZ_PLUS_1`.

I also checked the generated A5 kernel for the failing case. It goes through a V2C path using `TPipe<..., Direction::DIR_V2C, ...>` and emits `TPUSH(...)` on the AIV side, which reaches this stale `NZ_PLUS_1` reference during compilation.
