### PR TITLE
fix(a5): restore cross-core TPush TInsert compatibility

### LINKED ISSUE #94: [Bug] 0dcce451 breaks A5 cross-core TPUSH compilation with missing TInsertMode::NZ_PLUS_1
### Component

A5 backend (`include/pto/npu/a5/*`), cross-core `TPUSH` / V2C path

### Description

A5 cross-core kernels stop compiling starting from commit `0dcce451ea95f7fd42e090c559dfaacc3b04494f`.

The failure happens because `include/pto/npu/a5/TInsert.hpp` no longer defines `TInsertMode::NZ_PLUS_1`, but `include/pto/npu/a5/TPush.hpp` still references `TInsertMode::NZ_PLUS_1` in `pushVec2MatFiFo()` for the split-M vector-to-matrix FIFO path.

### Steps to Reproduce

1. Checkout `pto-isa` at `0dcce451ea95f7fd42e090c559dfaacc3b04494f`.
2. Use this ISA revision with PyPTO on A5 hardware.
3. Run:

```bash
pytest tests/st/runtime/test_cross_core.py -k test_tpush_tpop_v2c_updown -v --forked --device 0 --platform a5
```

I also reproduced this with the full cross-core suite:

```bash
pytest tests/st/runtime/test_cross_core.py -v --forked --device 0 --platform a5
```

### Expected Behavior

The A5 cross-core test should compile and run successfully.

This works with last known good commit `54c7c6dcfab5c21d523de6939bf8d7b305c5a804`.

### Actual Behavior

Compilation fails in the A5 ISA headers with:

```text
error: no member named 'NZ_PLUS_1' in 'pto::TInsertMode'
```

The failing reference is in `include/pto/npu/a5/TPush.hpp` inside `pushVec2MatFiFo()`, where the split-M path still instantiates `TINSERT_IMPL<TInsertMode::NZ_PLUS_1>(...)`.

### Git Commit ID

First bad commit: `0dcce451ea95f7fd42e090c559dfaacc3b04494f`

Last good commit: `54c7c6dcfab5c21d523de6939bf8d7b305c5a804`

### NPU Kind

Ascend 950 (A5)

### Host Platform

Linux (aarch64)

### Additional Context

The regression range is:

- Good: `54c7c6dcfab5c21d523de6939bf8d7b305c5a804`
- Bad: `0dcce451ea95f7fd42e090c559dfaacc3b04494f` (`add Tinsert vec-to-vec, ub2l1 unaligned, fp4/hif8 dtype`)

What changed across that boundary:

- In `include/pto/npu/a5/TInsert.hpp`, `TInsertMode` was reduced to only `SPLIT2` and `SPLIT4`.
- In `include/pto/npu/a5/TPush.hpp`, the A5 vector-to-matrix FIFO path still uses `TInsertMode::NZ_PLUS_1`.

I also checked the generated A5 kernel for the failing case. It goes through a V2C path using `TPipe<..., Direction::DIR_V2C, ...>` and emits `TPUSH(...)` on the AIV side, which reaches this stale `NZ_PLUS_1` reference during compilation.

### PR DESCRIPTION
**Pull request by lwDavid**
## Summary

  This PR fixes #94: an A5 cross-core regression in the `TPush` Vec-to-Mat FIFO path.

  On commit `54c7c6dc`, `tests/st/runtime/test_cross_core.py` passed on A5 board. On current `main`, the same test
  suite failed during incore compilation because `TPush` still referenced the removed `TInsertMode::NZ_PLUS_1` mode
  after the A5 `TInsert` refactor.

  ## Root Cause

  The A5 `TInsert` refactor removed the legacy `TInsertMode::NZ_PLUS_1` enum and consolidated the NZ insertion
  behavior into the default `TINSERT_IMPL(...)` path.

  However, one split-M branch in `include/pto/npu/a5/TPush.hpp` was left behind and still instantiated:

  `TINSERT_IMPL<TInsertMode::NZ_PLUS_1>(...)`

  As a result, all A5 cross-core runtime cases failed to compile with:

  `no member named 'NZ_PLUS_1' in 'pto::TInsertMode'`

  ## Fix

  Replace the stale `TInsertMode::NZ_PLUS_1` call in the split-M `pushVec2MatFiFo` path with the current default
  `TINSERT_IMPL(...)` call.

  This makes the split-M path consistent with the already-updated split-N and no-split paths and restores
  compatibility with the current A5 `TInsert` interface.

  ## Validation

  Validated on A5 board with:

  ```bash
  task-submit --run --device 0 "pytest tests/st/runtime/test_cross_core.py -v --forked --device 0 --platform a5"

  Result:

  9 passed

### CODE REVIEW

File: include/pto/npu/a5/TPush.hpp [hunk 1]
```diff
@@ -850,12 +850,7 @@ struct TMPipe {
                 uint64_t entryBase = (tile_id % DataFiFo::fifoDepth) * ConsM * ConsN * sizeof(T);
                 TileDataCons matTile;
                 TASSIGN_IMPL(matTile, fifo.fifoBase + entryBase);
-                constexpr bool isNZPlus1 = (ConsM / ProdM) != 2;
-                if constexpr (isNZPlus1) { // NZ + 1 mode
-                    TINSERT_IMPL<TInsertMode::NZ_PLUS_1>(matTile, tile, row_offset, 0);
-                } else {                   // NZ mode
-                    TINSERT_IMPL(matTile, tile, static_cast<uint16_t>(row_offset), static_cast<uint16_t>(0));
-                }
+                TINSERT_IMPL(matTile, tile, static_cast<uint16_t>(row_offset), static_cast<uint16_t>(0));
```
[the remark this answers is not in the document]
Comment (lwDavid) [reply include/pto/npu/a5/TPush.hpp:852]: Addressed. `entryOffset` now stays in the FIFO base address, split-M only offsets rows by `get_subblockid()`, and split-N now uses `ProdN * get_subblockid()`. Revalidated with the full A5 `test_cross_core.py` suite.
